import type { PublicAgent } from "@/lib/agents";

export const DEMO_AGENTS: PublicAgent[] = [
  {
    id: 101,
    user_id: 1001,
    slug: "marcus-vance",
    headline: "Luxury Estate Specialist & Top 1% Producer",
    bio: "Over 12 years of experience negotiating ultra-luxury residential sales, waterfront estates, and off-market penthouses in South Florida and California.",
    brokerage_name: "Domestic Elite Realty",
    license_number: "RE-984021-FL",
    years_experience: 14,
    specialties: ["Luxury Homes", "Waterfront Estates", "Off-Market Seller Leads", "Penthouse Sales"],
    service_areas: ["Miami", "Palm Beach", "Beverly Hills", "Malibu"],
    office_city: "Miami",
    office_state: "FL",
    office_phone: "+1 (305) 555-0192",
    office_email: "marcus.vance@domesticrealestate.us",
    rating: "4.95",
    review_count: 68,
    sales_count: 142,
    is_featured: true,
    user: {
      id: 1001,
      name: "Marcus Vance",
      email: "marcus@domesticrealestate.us",
      phone: "+1 (305) 555-0192",
      avatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&auto=format&fit=crop&q=80",
    },
  },
  {
    id: 102,
    user_id: 1002,
    slug: "sophia-chen",
    headline: "Commercial & Multi-Family Investment Advisor",
    bio: "Specializing in commercial acquisitions, triple-net leases, and high-ROI multi-family residential portfolios for institutional investors.",
    brokerage_name: "Apex Commercial Group",
    license_number: "RE-772109-NY",
    years_experience: 10,
    specialties: ["Commercial Real Estate", "Multi-Family Units", "ROI Analysis", "Wholesale Leads"],
    service_areas: ["New York", "Brooklyn", "Queens", "Jersey City"],
    office_city: "New York",
    office_state: "NY",
    office_phone: "+1 (212) 555-0844",
    office_email: "sophia.chen@domesticrealestate.us",
    rating: "4.90",
    review_count: 52,
    sales_count: 98,
    is_featured: true,
    user: {
      id: 1002,
      name: "Sophia Chen",
      email: "sophia@domesticrealestate.us",
      phone: "+1 (212) 555-0844",
      avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80",
    },
  },
  {
    id: 103,
    user_id: 1003,
    slug: "david-rodriguez",
    headline: "Residential & First-Time Homebuyer Expert",
    bio: "Helping families and buyers navigate home purchases with seamless negotiation, market analysis, and tailored buyer guidance.",
    brokerage_name: "Sunbelt Heritage Properties",
    license_number: "RE-549102-TX",
    years_experience: 8,
    specialties: ["Single Family Homes", "First-Time Buyers", "Relocation", "Suburban Developments"],
    service_areas: ["Austin", "Round Rock", "Dallas", "Fort Worth"],
    office_city: "Austin",
    office_state: "TX",
    office_phone: "+1 (512) 555-0371",
    office_email: "david.rodriguez@domesticrealestate.us",
    rating: "4.88",
    review_count: 41,
    sales_count: 76,
    is_featured: false,
    user: {
      id: 1003,
      name: "David Rodriguez",
      email: "david@domesticrealestate.us",
      phone: "+1 (512) 555-0371",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80",
    },
  },
  {
    id: 104,
    user_id: 1004,
    slug: "elena-rostova",
    headline: "Architectural Design & Modern Luxury Homes",
    bio: "Expert in architectural marvels, modern luxury builds, and eco-friendly sustainable smart homes.",
    brokerage_name: "Vanguard Modern Living",
    license_number: "RE-610933-CA",
    years_experience: 11,
    specialties: ["Modern Architecture", "Smart Homes", "Luxury Condos", "Interior Design"],
    service_areas: ["Los Angeles", "Santa Monica", "Pasadena"],
    office_city: "Los Angeles",
    office_state: "CA",
    office_phone: "+1 (310) 555-0922",
    office_email: "elena.rostova@domesticrealestate.us",
    rating: "4.92",
    review_count: 60,
    sales_count: 110,
    is_featured: true,
    user: {
      id: 1004,
      name: "Elena Rostova",
      email: "elena@domesticrealestate.us",
      phone: "+1 (310) 555-0922",
      avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&auto=format&fit=crop&q=80",
    },
  },
  {
    id: 105,
    user_id: 1005,
    slug: "james-montgomery",
    headline: "Wholesale & Distressed Property Specialist",
    bio: "Connecting fix-and-flip investors and wholesalers with high-margin off-market probate and distressed properties.",
    brokerage_name: "Keystone Investment Realty",
    license_number: "RE-401928-GA",
    years_experience: 9,
    specialties: ["Wholesale Deals", "Fix & Flip", "Probate & Distressed", "Cash Buyers"],
    service_areas: ["Atlanta", "Alpharetta", "Marietta"],
    office_city: "Atlanta",
    office_state: "GA",
    office_phone: "+1 (404) 555-0619",
    office_email: "james.montgomery@domesticrealestate.us",
    rating: "4.85",
    review_count: 35,
    sales_count: 88,
    is_featured: false,
    user: {
      id: 1005,
      name: "James Montgomery",
      email: "james@domesticrealestate.us",
      phone: "+1 (404) 555-0619",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80",
    },
  },
  {
    id: 106,
    user_id: 1006,
    slug: "victoria-sterling",
    headline: "Equestrian & Ranch Land Specialist",
    bio: "Dedicated advisor for luxury ranches, agricultural land holdings, and equestrian estates across North America.",
    brokerage_name: "Sterling Land & Farm Co.",
    license_number: "RE-881204-CO",
    years_experience: 16,
    specialties: ["Ranches & Land", "Equestrian Estates", "Farm Land", "Mountain Retreats"],
    service_areas: ["Denver", "Aspen", "Boulder", "Vail"],
    office_city: "Denver",
    office_state: "CO",
    office_phone: "+1 (303) 555-0488",
    office_email: "victoria.sterling@domesticrealestate.us",
    rating: "4.98",
    review_count: 79,
    sales_count: 165,
    is_featured: true,
    user: {
      id: 1006,
      name: "Victoria Sterling",
      email: "victoria@domesticrealestate.us",
      phone: "+1 (303) 555-0488",
      avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&auto=format&fit=crop&q=80",
    },
  },
];
