name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - "laravel-api/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          printf "%s" "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -p ${{ secrets.PORT }} ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Deploy Laravel
        run: |
          rsync -az --delete \
          -e "ssh -i ~/.ssh/deploy_key -p ${{ secrets.PORT }}" \
          --exclude=.env \
          --exclude=vendor \
          laravel-api/ \
          ${{ secrets.USERNAME }}@${{ secrets.HOST }}:~/domains/domesticrealestate.us/public_html/laravel-api/

      - name: Optimize Laravel
        run: |
          ssh -i ~/.ssh/deploy_key -p ${{ secrets.PORT }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} << EOF
          cd ~/domains/domesticrealestate.us/public_html/laravel-api
          composer install --no-dev --optimize-autoloader
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          EOF
